config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    allowed_params = %i[name]
    devise_parameter_sanitizer.permit(:sign_up, keys: allowed_params)
    devise_parameter_sanitizer.permit(:account_update, keys: allowed_params)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_member!, except: %i[index show]
  before_action :authorize_member!, except: %i[index show create new]

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:member).order(updated_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_member.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    # block actions if member is not owner of post
    def authorize_member!
      if @post.member.nil? || @post.member.id != current_member.id
        redirect_to post_path(@post), alert: "You are not the author of the post!"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/elements/_icon.html.erb
<%#= render "elements/icon", icon: :app %>

<%# default variables %>
<% size = "1em" if local_assigns[:size].nil? %>
<% color = "#212529" if local_assigns[:color].nil? %>
<i class="bi-<%= icon %>" style="font-size: <%= size %>; color: <%= color %>;"></i>

app/views/elements/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <p class="is-size-4">Members Only!</p>
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <% if member_signed_in? %>

        <div class="navbar-item">
          <div class="buttons">
            <%= link_to 'New Post', new_post_path, class: "button is-info" %>
            <%= link_to "Edit profile", edit_member_registration_path, class: "button" %>
            <%= link_to "Log out", destroy_member_session_path, method: :delete, class: "button" %>
          </div>
        </div>

      <% else %>

        <div class="navbar-item">
          <div class="buttons">
            <%= link_to raw("<strong>Sign up</strong>"), new_member_registration_path, class: "button is-info" %>
            <%= link_to "Log in", new_member_session_path, class: "button is-light" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</nav>
<script>
  document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

      // Add a click event on each of them
      $navbarBurgers.forEach(el => {
        el.addEventListener('click', () => {

          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }

  });
</script>

app/views/elements/_notifications.html.erb
<% if notice %>
  <div class="notification is-radiusless is-info">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="notification is-radiusless is-danger">
    <%= alert %>
  </div>
<% end %>

app/views/elements/_post_item.html.erb
<% # get author
author = if member_signed_in?
  if post.member
    post.member.name
  else
    "[Author deleted]"
  end
end %>

<div class="post-item box">
  <% if member_signed_in? %>

    <div class="is-flex is-size-5 is-justify-content-space-between">

      <h2>
        <%= link_to post.title, post_path(post), class: "has-text-black has-text-weight-light" %>
      </h2>

      <% if post.member && post.member == current_member %>
        <span class="is-flex-shrink-0">
          <a href="<%= edit_post_path(post) %>">
            <%= render "elements/icon", icon: "pencil-fill", color: :cornflowerblue %>
          </a>
          <a href="<%= post_path(post) %>" data-confirm="Are you sure?" rel="nofollow" data-method="delete">
            <%= render "elements/icon", icon: "trash-fill", color: :cornflowerblue %>
          </a>
        </span>
      <% end %>

    </div>

    <p class="has-text-weight-light"><%= author %></p>

  <% else %>

    <h2 class="is-size-5">
      <%= link_to post.title, post_path(post), class: "has-text-black has-text-weight-light" %>
    </h2>
  
  <% end %>

  <div class="content mt-2 mb-3">
    <%= post.content %>
  </div>

  <div class="post-metadata">
    <p class="is-italic has-text-weight-light is-size-7">Posted at <%= post.created_at.strftime "%Y-%m-%d %l:%M%P" %></p>
    <% if post.created_at != post.updated_at %>
      <p class="is-italic has-text-weight-light is-size-7">Updated at <%= post.updated_at.strftime "%Y-%m-%d %l:%M%P" %></p>
    <% end %>
  </div>
</div>

app/views/elements/_post_list.html.erb
<article class="post-list-item">
  <h1>
    <a href="<%= post_path(post.id) %>">
      <%= post.title %>
    </a>
  </h1>
  <p><span>By <%= post.member.name %></span></p>
  <p><%= post.content %></p>
  <div class="post-metadata">
    <p>Posted at <%= post.created_at.strftime "%Y-%m-%d %l:%M%P" %></p>
    <% if post.created_at != post.updated_at %>
      <p>Updated at <%= post.updated_at.strftime "%Y-%m-%d %l:%M%P" %></p>
    <% end %>
  </div>
</article>

app/views/elements/_post_page.html.erb
<% # get author
author = if member_signed_in?
  if post.member
    post.member.name
  else
    "[Author deleted]"
  end
end %>

<h2 class="is-size-5 has-text-black has-text-weight-light">
  <%= post.title %>
</h2>

<% if member_signed_in? %>
  <p class="has-text-weight-light"><%= author %></p>
<% end %>

<div class="content mt-2 mb-3">
  <%= post.content %>
</div>

<div class="post-metadata">
  <p class="is-italic has-text-weight-light is-size-7">Posted at <%= post.created_at.strftime "%Y-%m-%d %l:%M%P" %></p>
  <% if post.created_at != post.updated_at %>
    <p class="is-italic has-text-weight-light is-size-7">Updated at <%= post.updated_at.strftime "%Y-%m-%d %l:%M%P" %></p>
  <% end %>
</div>

<br>

<ul>
  <% if member_signed_in? && post.member && post.member == current_member %>
    <li>
      <a href="<%= edit_post_path(post) %>">
        <%= render "elements/icon", icon: "pencil-fill", color: :cornflowerblue %>
        Edit post
      </a>
    </li>
    <li>
      <a href="<%= post_path(post) %>" data-confirm="Are you sure?" rel="nofollow" data-method="delete">
        <%= render "elements/icon", icon: "trash-fill", color: :cornflowerblue %>
        Destroy post
      </a>
    </li>
  <% end %>
  <li>
    <a href="<%= posts_path %>">
      <%= render "elements/icon", icon: "arrow-return-left", color: :cornflowerblue %>
      Back
    </a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "elements/navbar" %>

    <%= render "elements/notifications" %>

    <div class="container mt-2">

      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label" %>
    <div class="control">
      <%= form.text_field :title, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :content, class: "label" %>
    <div class="control">
      <%= form.text_area :content, class: "textarea" %>
    </div>
  </div>

  <br>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit class: "button is-info" %>
    </div>
    <% if (defined? show_post) && show_post == true %>
      <div class="control">
        <%= link_to 'Back', @post, class: "button is-info is-light" %>
      </div>
    <% else %>
      <div class="control">
        <%= link_to 'Back', posts_path, class: "button is-info is-light" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="columns">
  <div id="post-list" class="column is-10 is-offset-1">
    <div class="box">
      <h1 class="is-size-4">Editing Post</h1>

      <br>

      <%= render 'form', post: @post, show_post: true %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="columns">
  <div id="post-list" class="column is-two-thirds is-offset-2">
    <% @posts.each do |post| %>
      <%= render "elements/post_item", post: post %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="columns">
  <div id="post-list" class="column is-10 is-offset-1">
    <div class="box">
      <h1 class="is-size-4">New Post</h1>

      <br>

      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="columns">
  <div id="post-list" class="column is-10 is-offset-1">
    <div class="box">
      <%= render "elements/post_page", post: @post %>
    </div>
  </div>
</div>